version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
  Server:
    container_name: Server
    image: "chazari/hmtpk_schedule_api:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: [ "/app/main", "Server"]