version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
  http-schedule-server:
    container_name: http-schedule-server
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: [ "/app/main", "http"]
  grpc-schedule-server:
    container_name: http-schedule-server
    build: .
    ports:
      - "50051:50051"
    restart: always
    command: [ "/app/main", "grpc"]