redis:
  host: 0.0.0.0
  port: :6379
  password: pass
server:
  http:
    domain: localhost
    http_address: :8080
    https_address: ""
    mini_app_token: token
  grpc:
    domain: localhost
    address: :50051
    mini_app_token: token