redis:
  host: redis
  port: :6379
  password: password
server:
  http:
    domain: hmtpksch.chazari.ru
    http_address: :80
    https_address: :443
  grpc:
    domain: hmtpksch.chazari.ru
    address: :50051
