redis:
  host: schedule-redis
  port: :6379
  password: password
server:
  http:
    domain: hmtpksch.chazari.ru
    http_address: :80
    https_address: :443
    mini_app_token: token
  grpc:
    domain: hmtpksch.chazari.ru
    address: :50051
    mini_app_token: token